***<h1 style="color:Lightred;">🇱🇧 Lebanese AI Assistant</h1>***
*<h2 style="color:Lightgreen;">Fine-tuning Qwen2.5 with LoRA (Unsloth)</h2>*
____________________________________________________________________________

 <h3 style="color:pink;">Libraries Imported</h3>

In [11]:
import pandas as pd       #import pandas library for data manipulation and analysis
import ast                # keep the data in the same format as it is in the csv file

 <h3 style="color:pink;">Reading the Dataset</h3>

In [13]:
df = pd.read_csv(r'C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\raw\ultrachats\train_sft.csv')

In [14]:
df.columns      #check the column names of the dataset to understand the structure of the data
df.iloc[0]      #check the first row of the dataset to understand the format and content of the data

prompt       These instructions apply to section-based them...
prompt_id    f0e37e9f7800261167ce91143f98f511f768847236f133...
messages     [{'content': "These instructions apply to sect...
Name: 0, dtype: object

In [15]:
df.head()      # for a quick overview of the data

,prompt,prompt_id,messages
0,These instructions apply to section-based them...,f0e37e9f7800261167ce91143f98f511f768847236f133...,"[{'content': ""These instructions apply to sect..."
1,Which famous landmarks should I visit in Londo...,f5025bdcae61bb77fd98a4d6cd6ba8e0199a098cfebcf6...,[{'content': 'Which famous landmarks should I ...
2,Write a comprehensive blog post of at least 10...,6db663a4d2671b41e0038c43c39f79cf909b10987dc595...,"[{'content': ""Write a comprehensive blog post ..."
3,"De León, previewing the speech he will give to...",dd1afba7d2151b0695edea838378c8fd086d538e62a664...,"[{'content': 'De León, previewing the speech h..."
4,Write an essay that evaluates the positive and...,cbf683405d8fe0221a42560cec50307d5fa9efa160c49d...,[{'content': 'Write an essay that evaluates th...

In [16]:
type(df['messages'][0])   # to understand the data format
print(df["messages"][0])  #  to understand the structure of the data in that column

[{'content': "These instructions apply to section-based themes (Responsive 6.0+, Retina 4.0+, Parallax 3.0+ Turbo 2.0+, Mobilia 5.0+). What theme version am I using?\nOn your Collections pages & Featured Collections sections, you can easily show the secondary image of a product on hover by enabling one of the theme's built-in settings!\nYour Collection pages & Featured Collections sections will now display the secondary product image just by hovering over that product image thumbnail.\nDoes this feature apply to all sections of the theme or just specific ones as listed in the text material?", 'role': 'user'}
 {'content': 'This feature only applies to Collection pages and Featured Collections sections of the section-based themes listed in the text material.', 'role': 'assistant'}
 {'content': 'Can you guide me through the process of enabling the secondary image hover feature on my Collection pages and Featured Collections sections?', 'role': 'user'}
 {'content': "Sure, here are the steps to enable the secondary image hover feature on your Collection pages and Featured Collections sections:\n\n1. Log in to your Shopify account and go to your Online Store.\n2. Click on Customize theme for the section-based theme you are using.\n3. Navigate to the Collection pages or Featured Collections section where you want to enable the secondary image hover feature.\n4. With the section open, click on the section's setting (gear) icon in the top-left corner.\n5. In the settings panel that appears, look for an option labeled 'Image display' or 'Image hover'.\n6. If available, select 'Show secondary image on hover'.\n7. Save the changes and preview the Collection/Featured Collection page to see the effect.\n\nIf you're having trouble finding the setting, the best thing to do is refer to your theme's documentation, since the location and labeling of settings can vary between themes.", 'role': 'assistant'}
 {'content': 'Can you provide me with a link to the documentation for my theme?', 'role': 'user'}
 {'content': "I don't have access to your store's theme information. However, you can usually find the documentation for your theme by going to the shopify theme store, finding your theme and clicking on the 'support' link located in the bottom right corner of the page. Alternatively, you can do a google search for the name of your theme followed by 'documentation' or 'user guide'.", 'role': 'assistant'}
 {'content': 'Can you confirm if this feature also works for the Quick Shop section of my theme?', 'role': 'user'}
 {'content': "The secondary image hover feature may or may not work for your Quick Shop section, depending on the configuration of your theme. Some themes include this feature in the Quick Shop section by default, while others may require additional customization. To check if this feature is available for the Quick Shop section of your theme, follow these steps:\n\n1. Go to the Quick Shop section where you would like to enable the feature. 2. Click on the Quick Shop settings icon (gear icon) and look for 'Image display' or 'Image hover'. 3. If available, select 'Show secondary image on hover'. 4. Save the changes. If this option is not available in your Quick Shop section settings, you may need to reach out to your theme developer for assistance with customizing your Quick Shop section to include this feature.", 'role': 'assistant'}]

In [17]:
print('The dataset size : ',len(df)) # to understand the size of the data we are working with

The dataset size :  207865

In [18]:
df.info()   #to get a concise summary of the DataFrame, including the number of non-null entries and data types of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207865 entries, 0 to 207864
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   prompt     207864 non-null  object
 1   prompt_id  207865 non-null  object
 2   messages   207865 non-null  object
dtypes: object(3)
memory usage: 4.8+ MB

In [19]:
df.isnull().sum() # check for missing values in dataset

prompt       1
prompt_id    0
messages     0
dtype: int64

In [20]:
type(df["messages"][0])  #check data type of 1st element in 'messages' column to confirm if it is a string

str

In [21]:
msg = df["messages"][0] # check content of 1st element to understand the structure of the data in that column
print(type(msg)) # to confirm the data type of the content in the 'messages' column
print(repr(msg[:1000])) # to check the first 1000 characters of the content in the 'messages' column to understand its structure and format

<class 'str'>
'[{\'content\': "These instructions apply to section-based themes (Responsive 6.0+, Retina 4.0+, Parallax 3.0+ Turbo 2.0+, Mobilia 5.0+). What theme version am I using?\\nOn your Collections pages & Featured Collections sections, you can easily show the secondary image of a product on hover by enabling one of the theme\'s built-in settings!\\nYour Collection pages & Featured Collections sections will now display the secondary product image just by hovering over that product image thumbnail.\\nDoes this feature apply to all sections of the theme or just specific ones as listed in the text material?", \'role\': \'user\'}\n {\'content\': \'This feature only applies to Collection pages and Featured Collections sections of the section-based themes listed in the text material.\', \'role\': \'assistant\'}\n {\'content\': \'Can you guide me through the process of enabling the secondary image hover feature on my Collection pages and Featured Collections sections?\', \'role\': \'user\'}\n {\'content\': "Sure, here are the step'

In [22]:
conversation_raw = df["messages"][0] #krml n3ml parsing l string l raw l list of dictionaries

print(conversation_raw.count("'role': 'user'")) #Krml n3rf kam marra l user 7ki b l dataset
print(conversation_raw.count("'role': 'assistant'")) #krml n3rf kam marra l assistant 7ki b l dataset

4
4

In [23]:
print(conversation_raw[:2000]) #krml n3rf shou l format l raw l list of dictionaries 3m yb2a 3ndo w shou l structure l messages b l dataset

[{'content': "These instructions apply to section-based themes (Responsive 6.0+, Retina 4.0+, Parallax 3.0+ Turbo 2.0+, Mobilia 5.0+). What theme version am I using?\nOn your Collections pages & Featured Collections sections, you can easily show the secondary image of a product on hover by enabling one of the theme's built-in settings!\nYour Collection pages & Featured Collections sections will now display the secondary product image just by hovering over that product image thumbnail.\nDoes this feature apply to all sections of the theme or just specific ones as listed in the text material?", 'role': 'user'}
 {'content': 'This feature only applies to Collection pages and Featured Collections sections of the section-based themes listed in the text material.', 'role': 'assistant'}
 {'content': 'Can you guide me through the process of enabling the secondary image hover feature on my Collection pages and Featured Collections sections?', 'role': 'user'}
 {'content': "Sure, here are the steps to enable the secondary image hover feature on your Collection pages and Featured Collections sections:\n\n1. Log in to your Shopify account and go to your Online Store.\n2. Click on Customize theme for the section-based theme you are using.\n3. Navigate to the Collection pages or Featured Collections section where you want to enable the secondary image hover feature.\n4. With the section open, click on the section's setting (gear) icon in the top-left corner.\n5. In the settings panel that appears, look for an option labeled 'Image display' or 'Image hover'.\n6. If available, select 'Show secondary image on hover'.\n7. Save the changes and preview the Collection/Featured Collection page to see the effect.\n\nIf you're having trouble finding the setting, the best thing to do is refer to your theme's documentation, since the location and labeling of settings can vary between themes.", 'role': 'assistant'}
 {'content': 'Can you provide me with a link to the documentation for my theme?'

In [24]:
conversation = ast.literal_eval(df["messages"][0])  #krml n3ml parsing l string l raw l list of dictionaries b l dataset krml n2dr nst5dmha b l code w n3rf shou l structure l messages b l dataset
print(type(conversation)) 
print(conversation[0])  #krml n3rf shou format l conversation ba3d ma 3mlna parsing l string l raw l list of dictionaries b l dataset 
print(conversation[0]["role"]) #krml n3rf shou l value l role l awl message b l conversation ba3d ma 3mlna parsing 
print(conversation[0]["content"][:200])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)

# insights for context window yale rh ytdrb l model 3lya

In [ ]:
conversation_lengths = [] 

for msg in df["messages"][:100]: 
    conversation_lengths.append(msg.count("'role':"))
print("Average messages:", sum(conversation_lengths) / len(conversation_lengths)) 
print("Min messages:", min(conversation_lengths)) 
print("Max messages:", max(conversation_lengths))

# ultrachat isn't Q/A dataset , hye cconversation history

Average messages: 6.96
Min messages: 4
Max messages: 14

# Environment Setup        ✅
# Dataset Loading          ✅
# Dataset Exploration      ✅
# Dataset Analysis         ✅