# Goal is to clean the raw ultrachat dataset ad prepare it to be clean Qwen-ready converstations

## 🚀 STEP 1 - n3ml Fix ll messages format

### - 1st problem we noticed was that (Messages) are "String" they're not [Lists]
### - 2nd problem there're missing commas which give us invalid literal_eval() errors

In [1]:
import ast
import pandas as pd
import json 
from transformers import AutoTokenizer 
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\raw\ultrachats\train_sft.csv",
    engine="python",
    on_bad_lines="skip"
)

df.head()

,prompt,prompt_id,messages
0,These instructions apply to section-based them...,f0e37e9f7800261167ce91143f98f511f768847236f133...,"[{'content': ""These instructions apply to sect..."
1,Which famous landmarks should I visit in Londo...,f5025bdcae61bb77fd98a4d6cd6ba8e0199a098cfebcf6...,[{'content': 'Which famous landmarks should I ...
2,Write a comprehensive blog post of at least 10...,6db663a4d2671b41e0038c43c39f79cf909b10987dc595...,"[{'content': ""Write a comprehensive blog post ..."
3,"De León, previewing the speech he will give to...",dd1afba7d2151b0695edea838378c8fd086d538e62a664...,"[{'content': 'De León, previewing the speech h..."
4,Write an essay that evaluates the positive and...,cbf683405d8fe0221a42560cec50307d5fa9efa160c49d...,[{'content': 'Write an essay that evaluates th...

In [3]:
df = df[['messages']]
df.head()

                                            messages
0  [{'content': "These instructions apply to sect...
1  [{'content': 'Which famous landmarks should I ...
2  [{'content': "Write a comprehensive blog post ...
3  [{'content': 'De León, previewing the speech h...
4  [{'content': 'Write an essay that evaluates th...

### Fix Parsing

In [4]:
# safe parsing function hta n3ml handling ll different formats 
def safe_parse(x):
    if pd.isna(x):
        return None

    try:
        return ast.literal_eval(x)
    except:
        try:
            # fix broken UltraChat formatting
            x = x.replace("}\n {", "},\n {")
            return ast.literal_eval(x)
        except:
            return None

In [5]:
# Apply the safe parsing to the messages column 
df["parsed_messages"] = df["messages"].apply(safe_parse) # zdna column jdd w 3bayne b eemt messgs parsed 
print(len(df))

207866

### Must remove broken rows

In [6]:
df = df[df["parsed_messages"].notnull()].reset_index(drop=True) #bnsheel l rows mn l parsed msgs yle msh true w bnhton bl dataset

In [7]:
print(type(df["parsed_messages"].iloc[0]))
print(df["parsed_messages"].iloc[0][:2])

<class 'list'>
[{'content': "These instructions apply to section-based themes (Responsive 6.0+, Retina 4.0+, Parallax 3.0+ Turbo 2.0+, Mobilia 5.0+). What theme version am I using?\nOn your Collections pages & Featured Collections sections, you can easily show the secondary image of a product on hover by enabling one of the theme's built-in settings!\nYour Collection pages & Featured Collections sections will now display the secondary product image just by hovering over that product image thumbnail.\nDoes this feature apply to all sections of the theme or just specific ones as listed in the text material?", 'role': 'user'}, {'content': 'This feature only applies to Collection pages and Featured Collections sections of the section-based themes listed in the text material.', 'role': 'assistant'}]

In [8]:
def clean_conversation(messages):
    if not isinstance(messages, list):
        return []

    cleaned = []

    for m in messages:
        if isinstance(m, dict):
            role = m.get("role", "")
            content = m.get("content", "")
            cleaned.append(f"{role}: {content}")

    return cleaned

In [9]:
df["parsed_messages"].apply(type).value_counts()

parsed_messages
<class 'list'>    207863
Name: count, dtype: int64

In [10]:
df[df["parsed_messages"].isna()]

Empty DataFrame
Columns: [messages, parsed_messages]
Index: []

In [11]:
df["parsed_messages"] = df["parsed_messages"].apply(
    lambda x: x if isinstance(x, list) else []
)

In [12]:
df["clean_messages"] = df["parsed_messages"].apply(clean_conversation)

In [13]:
df = df[df["clean_messages"].apply(len) > 0]

In [14]:
def to_qwen(messages):
    return {
        "messages": messages
    }

In [15]:
df["qwen"] = df["clean_messages"].apply(to_qwen)

In [16]:
output_path = "../datasets/processed/qwen_dataset.jsonl"

with open(output_path, "w", encoding="utf-8") as f:
    for item in df["qwen"]:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

In [17]:
tokenizer = AutoTokenizer.from_pretrained(
    "Qwen/Qwen3-0.6B" ,  trust_remote_code=True
)

In [18]:
df

,messages,parsed_messages,clean_messages,qwen
0,"[{'content': ""These instructions apply to sect...",[{'content': 'These instructions apply to sect...,[user: These instructions apply to section-bas...,{'messages': ['user: These instructions apply ...
1,[{'content': 'Which famous landmarks should I ...,[{'content': 'Which famous landmarks should I ...,[user: Which famous landmarks should I visit i...,{'messages': ['user: Which famous landmarks sh...
2,"[{'content': ""Write a comprehensive blog post ...",[{'content': 'Write a comprehensive blog post ...,[user: Write a comprehensive blog post of at l...,{'messages': ['user: Write a comprehensive blo...
3,"[{'content': 'De León, previewing the speech h...","[{'content': 'De León, previewing the speech h...","[user: De León, previewing the speech he will ...","{'messages': ['user: De León, previewing the s..."
4,[{'content': 'Write an essay that evaluates th...,[{'content': 'Write an essay that evaluates th...,[user: Write an essay that evaluates the posit...,{'messages': ['user: Write an essay that evalu...
...,...,...,...,...
207858,"[{'content': ""Write a 5-7 page short story in ...",[{'content': 'Write a 5-7 page short story in ...,[user: Write a 5-7 page short story in third p...,{'messages': ['user: Write a 5-7 page short st...
207859,"[{'content': ""Write a natural-sounding dialogu...",[{'content': 'Write a natural-sounding dialogu...,[user: Write a natural-sounding dialogue betwe...,{'messages': ['user: Write a natural-sounding ...
207860,[{'content': 'Write instructions on how to mak...,[{'content': 'Write instructions on how to mak...,[user: Write instructions on how to make a del...,{'messages': ['user: Write instructions on how...
207861,[{'content': 'Write a heartfelt letter to a fa...,[{'content': 'Write a heartfelt letter to a fa...,[user: Write a heartfelt letter to a family me...,{'messages': ['user: Write a heartfelt letter ...
207862,[{'content': 'How does pancreatic tissue damag...,[{'content': 'How does pancreatic tissue damag...,[user: How does pancreatic tissue damage or in...,{'messages': ['user: How does pancreatic tissu...

In [19]:
df.columns

Index(['messages', 'parsed_messages', 'clean_messages', 'qwen'], dtype='object')

In [20]:
df.head(1)

,messages,parsed_messages,clean_messages,qwen
0,"[{'content': ""These instructions apply to sect...",[{'content': 'These instructions apply to sect...,[user: These instructions apply to section-bas...,{'messages': ['user: These instructions apply ...

In [21]:
df["qwen"].iloc[0]

{'messages': ["user: These instructions apply to section-based themes (Responsive 6.0+, Retina 4.0+, Parallax 3.0+ Turbo 2.0+, Mobilia 5.0+). What theme version am I using?\nOn your Collections pages & Featured Collections sections, you can easily show the secondary image of a product on hover by enabling one of the theme's built-in settings!\nYour Collection pages & Featured Collections sections will now display the secondary product image just by hovering over that product image thumbnail.\nDoes this feature apply to all sections of the theme or just specific ones as listed in the text material?",
  'assistant: This feature only applies to Collection pages and Featured Collections sections of the section-based themes listed in the text material.',
  'user: Can you guide me through the process of enabling the secondary image hover feature on my Collection pages and Featured Collections sections?',
  "assistant: Sure, here are the steps to enable the secondary image hover feature on your Collection pages and Featured Collections sections:\n\n1. Log in to your Shopify account and go to your Online Store.\n2. Click on Customize theme for the section-based theme you are using.\n3. Navigate to the Collection pages or Featured Collections section where you want to enable the secondary image hover feature.\n4. With the section open, click on the section's setting (gear) icon in the top-left corner.\n5. In the settings panel that appears, look for an option labeled 'Image display' or 'Image hover'.\n6. If available, select 'Show secondary image on hover'.\n7. Save the changes and preview the Collection/Featured Collection page to see the effect.\n\nIf you're having trouble finding the setting, the best thing to do is refer to your theme's documentation, since the location and labeling of settings can vary between themes.",
  'user: Can you provide me with a link to the documentation for my theme?',
  "assistant: I don't have access to your store's theme information. However, you can usually find the documentation for your theme by going to the shopify theme store, finding your theme and clicking on the 'support' link located in the bottom right corner of the page. Alternatively, you can do a google search for the name of your theme followed by 'documentation' or 'user guide'.",
  'user: Can you confirm if this feature also works for the Quick Shop section of my theme?',
  "assistant: The secondary image hover feature may or may not work for your Quick Shop section, depending on the configuration of your theme. Some themes include this feature in the Quick Shop section by default, while others may require additional customization. To check if this feature is available for the Quick Shop section of your theme, follow these steps:\n\n1. Go to the Quick Shop section where you would like to enable the feature. 2. Click on the Quick Shop settings icon (gear icon) and look for 'Image display' or 'Image hover'. 3. If available, select 'Show secondary image on hover'. 4. Save the changes. If this option is not available in your Quick Shop section settings, you may need to reach out to your theme developer for assistance with customizing your Quick Shop section to include this feature."]}

In [22]:
type(df["qwen"].iloc[0])

dict

In [23]:
type(df["qwen"].iloc[0]["messages"])

list

In [24]:
def convert_to_qwen(messages):
    conversation = []

    for msg in messages:
        if msg.startswith("user: "):
            conversation.append({
                "role": "user",
                "content": msg.replace("user: ", "", 1)
            })

        elif msg.startswith("assistant: "):
            conversation.append({
                "role": "assistant",
                "content": msg.replace("assistant: ", "", 1)
            })

    return conversation

In [25]:
df["qwen_messages"] = df["qwen"].apply(
    lambda x: convert_to_qwen(x["messages"])
)

In [26]:
df["qwen_messages"].iloc[0]

[{'role': 'user',
  'content': "These instructions apply to section-based themes (Responsive 6.0+, Retina 4.0+, Parallax 3.0+ Turbo 2.0+, Mobilia 5.0+). What theme version am I using?\nOn your Collections pages & Featured Collections sections, you can easily show the secondary image of a product on hover by enabling one of the theme's built-in settings!\nYour Collection pages & Featured Collections sections will now display the secondary product image just by hovering over that product image thumbnail.\nDoes this feature apply to all sections of the theme or just specific ones as listed in the text material?"},
 {'role': 'assistant',
  'content': 'This feature only applies to Collection pages and Featured Collections sections of the section-based themes listed in the text material.'},
 {'role': 'user',
  'content': 'Can you guide me through the process of enabling the secondary image hover feature on my Collection pages and Featured Collections sections?'},
 {'role': 'assistant',
  'content': "Sure, here are the steps to enable the secondary image hover feature on your Collection pages and Featured Collections sections:\n\n1. Log in to your Shopify account and go to your Online Store.\n2. Click on Customize theme for the section-based theme you are using.\n3. Navigate to the Collection pages or Featured Collections section where you want to enable the secondary image hover feature.\n4. With the section open, click on the section's setting (gear) icon in the top-left corner.\n5. In the settings panel that appears, look for an option labeled 'Image display' or 'Image hover'.\n6. If available, select 'Show secondary image on hover'.\n7. Save the changes and preview the Collection/Featured Collection page to see the effect.\n\nIf you're having trouble finding the setting, the best thing to do is refer to your theme's documentation, since the location and labeling of settings can vary between themes."},
 {'role': 'user',
  'content': 'Can you provide me with a link to the documentation for my theme?'},
 {'role': 'assistant',
  'content': "I don't have access to your store's theme information. However, you can usually find the documentation for your theme by going to the shopify theme store, finding your theme and clicking on the 'support' link located in the bottom right corner of the page. Alternatively, you can do a google search for the name of your theme followed by 'documentation' or 'user guide'."},
 {'role': 'user',
  'content': 'Can you confirm if this feature also works for the Quick Shop section of my theme?'},
 {'role': 'assistant',
  'content': "The secondary image hover feature may or may not work for your Quick Shop section, depending on the configuration of your theme. Some themes include this feature in the Quick Shop section by default, while others may require additional customization. To check if this feature is available for the Quick Shop section of your theme, follow these steps:\n\n1. Go to the Quick Shop section where you would like to enable the feature. 2. Click on the Quick Shop settings icon (gear icon) and look for 'Image display' or 'Image hover'. 3. If available, select 'Show secondary image on hover'. 4. Save the changes. If this option is not available in your Quick Shop section settings, you may need to reach out to your theme developer for assistance with customizing your Quick Shop section to include this feature."}]

In [27]:
sample = df["qwen_messages"].iloc[0]

formatted_text = tokenizer.apply_chat_template(
    sample,
    tokenize=False,
    add_generation_prompt=False
)

print(formatted_text[:2000])

<|im_start|>user
These instructions apply to section-based themes (Responsive 6.0+, Retina 4.0+, Parallax 3.0+ Turbo 2.0+, Mobilia 5.0+). What theme version am I using?
On your Collections pages & Featured Collections sections, you can easily show the secondary image of a product on hover by enabling one of the theme's built-in settings!
Your Collection pages & Featured Collections sections will now display the secondary product image just by hovering over that product image thumbnail.
Does this feature apply to all sections of the theme or just specific ones as listed in the text material?<|im_end|>
<|im_start|>assistant
This feature only applies to Collection pages and Featured Collections sections of the section-based themes listed in the text material.<|im_end|>
<|im_start|>user
Can you guide me through the process of enabling the secondary image hover feature on my Collection pages and Featured Collections sections?<|im_end|>
<|im_start|>assistant
Sure, here are the steps to enable the secondary image hover feature on your Collection pages and Featured Collections sections:

1. Log in to your Shopify account and go to your Online Store.
2. Click on Customize theme for the section-based theme you are using.
3. Navigate to the Collection pages or Featured Collections section where you want to enable the secondary image hover feature.
4. With the section open, click on the section's setting (gear) icon in the top-left corner.
5. In the settings panel that appears, look for an option labeled 'Image display' or 'Image hover'.
6. If available, select 'Show secondary image on hover'.
7. Save the changes and preview the Collection/Featured Collection page to see the effect.

If you're having trouble finding the setting, the best thing to do is refer to your theme's documentation, since the location and labeling of settings can vary between themes.<|im_end|>
<|im_start|>user
Can you provide me with a link to the documentation for my theme?<|im_end|>
<|im_start|>assistan

In [28]:
def format_chat(messages):
    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )

df["text"] = df["qwen_messages"].apply(format_chat)

In [29]:
print(df["text"].iloc[0][:500])

<|im_start|>user
These instructions apply to section-based themes (Responsive 6.0+, Retina 4.0+, Parallax 3.0+ Turbo 2.0+, Mobilia 5.0+). What theme version am I using?
On your Collections pages & Featured Collections sections, you can easily show the secondary image of a product on hover by enabling one of the theme's built-in settings!
Your Collection pages & Featured Collections sections will now display the secondary product image just by hovering over that product image thumbnail.
Does this

In [30]:
sample_df = df.sample(
    n=10000,
    random_state=42
)

In [31]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    sample_df,
    test_size=0.1,
    random_state=42
)

In [32]:
train_save = train_df[["text"]]
val_save = val_df[["text"]]

In [33]:
import json

train_save.to_json(
    r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed/train.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

val_save.to_json(
    r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed/val.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

In [34]:
import os

os.listdir("../datasets/processed")

['qwen_dataset.jsonl', 'train.jsonl', 'val.jsonl']

In [36]:
pd.read_json("../datasets/processed/train.jsonl", lines=True)

                                                   text
0     <|im_start|>user\nWrite instructions for makin...
1     <|im_start|>user\nGiven the text: Rotherham Un...
2     <|im_start|>user\nWhat are some unique outdoor...
3     <|im_start|>user\nCould you continue the story...
4     <|im_start|>user\nHow has Mozambique's cultura...
...                                                 ...
8995  <|im_start|>user\nCan you summarize the recent...
8996  <|im_start|>user\nCreate a comprehensive and i...
8997  <|im_start|>user\nCan you describe in detail t...
8998  <|im_start|>user\nWhat measures do African nat...
8999  <|im_start|>user\nWrite a comprehensive guide ...

[9000 rows x 1 columns]

In [38]:
import pandas as pd

val_df = pd.read_json(
    r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed\val.jsonl",
    lines=True
)

print(val_df.shape)

(1000, 1)

In [40]:
import pandas as pd

train_df = pd.read_json(
     r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed\train.jsonl",
    lines=True
)

print(train_df.columns)
print(train_df.head(1))

Index(['text'], dtype='object')
                                                text
0  <|im_start|>user\nWrite instructions for makin...

In [7]:
import json
import os

combined_file = r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed\finalDataset.jsonl"
print(f"--- 🔍 فحص ملف الداتا: {combined_file} ---")

try:
    with open(combined_file, "r", encoding="utf-8") as f:
        for i in range(2):
            line = f.readline()
            if not line:
                break
            data = json.loads(line)
            print(f"\n🔹 [السطر {i+1}] - نوع البيانات (Type): {type(data)}")
            if isinstance(data, dict):
                print(f"   المفاتيح الموجودة (Keys): {list(data.keys())}")
                
    with open(combined_file, "r", encoding="utf-8") as f:
        total_lines = sum(1 for line in f if line.strip())
    print(f"\n📊 إجمالي عدد الأسطر (Shape) في الملف هو: {total_lines} أسطر.")
except FileNotFoundError:
    print(f"❌ خطأ: ملف {combined_file} مش موجود! تأكد من المسار.")

--- 🔍 فحص ملف الداتا: C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed\finalDataset.jsonl ---

🔹 [السطر 1] - نوع البيانات (Type): <class 'dict'>
   المفاتيح الموجودة (Keys): ['text']

🔹 [السطر 2] - نوع البيانات (Type): <class 'dict'>
   المفاتيح الموجودة (Keys): ['messages']

📊 إجمالي عدد الأسطر (Shape) في الملف هو: 15000 أسطر.

In [8]:
import json
import re

combined_file = r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed\finalDataset.jsonl"

system_prompt = {
    "role": "system", 
    "content": "أنت مساعد ذكي لبناني. بتفهم وبتتكلم بالعامية اللبنانية وباللغة الإنجليزية بطلاقة، وأسلوبك دايماً قريب للقلب ومساعد."
}

all_clean_data = []
processed_count = 0
skipped_count = 0

print("⏳ جاري تفكيك النص واستخراج الـ 15,000 سطر بالكامل...")

with open(combined_file, "r", encoding="utf-8") as f:
    for idx, line in enumerate(f):
        if not line.strip(): continue
        try:
            data = json.loads(line)
            clean_messages_list = []
            
            # الشكل الأول: حقل 'messages' جاهز (الداتا اللبنانية)
            if isinstance(data, dict) and "messages" in data:
                raw_messages = data["messages"]
                for msg in raw_messages:
                    if isinstance(msg, dict):
                        clean_messages_list.append(msg)
                    elif isinstance(msg, str):
                        if msg.startswith("user:"):
                            clean_messages_list.append({"role": "user", "content": msg.replace("user:", "", 1).strip()})
                        elif msg.startswith("assistant:"):
                            clean_messages_list.append({"role": "assistant", "content": msg.replace("assistant:", "", 1).strip()})

            # الشكل الثاني: حقل 'text' وبداخله تاغات ChatML (داتا UltraChat المفرمتة)
            elif isinstance(data, dict) and "text" in data:
                text_content = data["text"]
                pattern = r"<\|im_start\|>(user|assistant|system)\n(.*?)(?=<\|im_end\|>)"
                matches = re.findall(pattern, text_content, re.DOTALL)
                for role, content in matches:
                    clean_messages_list.append({"role": role, "content": content.strip()})
            else:
                skipped_count += 1
                continue
                
            if not clean_messages_list:
                skipped_count += 1
                continue
                
            if clean_messages_list[0].get("role") == "system":
                clean_messages_list = clean_messages_list[1:]
            
            clean_row = {"messages": [system_prompt] + clean_messages_list}
            all_clean_data.append(clean_row)
            processed_count += 1
        except json.JSONDecodeError:
            skipped_count += 1
            continue

print(f"\n✨ انتهت المعالجة الشاملة بنجاح ساحق!")
print(f"✅ إجمالي الأسطر المستخرجة والمظبطة: {processed_count}")
print(f"⚠️ أسطر خربانة أو فارغة وتم تخطيها: {skipped_count}")

⏳ جاري تفكيك النص واستخراج الـ 15,000 سطر بالكامل...

✨ انتهت المعالجة الشاملة بنجاح ساحق!
✅ إجمالي الأسطر المستخرجة والمظبطة: 15000
⚠️ أسطر خربانة أو فارغة وتم تخطيها: 0

In [9]:
import random

print("🎲 جاري خلط البيانات عشوائياً (Shuffling)...")
random.shuffle(all_clean_data)
print("✅ تم خلط البيانات بنجاح!")

🎲 جاري خلط البيانات عشوائياً (Shuffling)...
✅ تم خلط البيانات بنجاح!

In [11]:
import json
import os

split_ratio = 0.9
split_index = int(len(all_clean_data) * split_ratio)

train_data = all_clean_data[:split_index]
eval_data = all_clean_data[split_index:]

output_dir = r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed"
train_path = os.path.join(output_dir, "train.jsonl")
eval_path = os.path.join(output_dir, "eval.jsonl")

print("💾 جاري حفظ ملفات الـ JSONL الجديدة الحقيقية...")
with open(train_path, "w", encoding="utf-8") as f:
    for row in train_data:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

with open(eval_path, "w", encoding="utf-8") as f:
    for row in eval_data:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

print(f"\n🎉 انتهت المرحلة الأولى! الملفات انحفظت بـ: {output_dir}")
print(f"📝 ملف التدريب (train.jsonl): {len(train_data)} سطر.")
print(f"📊 ملف التقييم (eval.jsonl): {len(eval_data)} سطر.")

💾 جاري حفظ ملفات الـ JSONL الجديدة الحقيقية...

🎉 انتهت المرحلة الأولى! الملفات انحفظت بـ: C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed
📝 ملف التدريب (train.jsonl): 13500 سطر.
📊 ملف التقييم (eval.jsonl): 1500 سطر.

In [14]:
import json
import os

# مسارات الملفات التي تم إنشاؤها
output_dir = r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed"
train_path = os.path.join(output_dir, "train.jsonl")
eval_path = os.path.join(output_dir, "eval.jsonl")

def validate_qwen_dataset(file_path):
    print(f"\n--- ⏳ جاري الفحص الدقيق لملف: {os.path.basename(file_path)} ---")
    
    if not os.path.exists(file_path):
        print(f"❌ خطأ: الملف غير موجود على المسار المحدد!")
        return False
        
    errors = 0
    null_count = 0
    wrong_format_count = 0
    total_rows = 0
    
    with open(file_path, "r", encoding="utf-8") as f:
        for idx, line in enumerate(f):
            if not line.strip():
                continue
            total_rows += 1
            
            try:
                data = json.loads(line)
                
                # 1. فحص الهيكل الأساسي (يجب أن يحتوي على messages وتكون لستة)
                if not isinstance(data, dict) or "messages" not in data or not isinstance(data["messages"], list):
                    print(f"🚨 [السطر {idx+1}]: خطأ في الهيكل الأساسي! (يجب أن يكون Dict يحتوي على لستة messages)")
                    wrong_format_count += 1
                    errors += 1
                    continue
                
                messages = data["messages"]
                
                # 2. فحص محتوى الرسائل بالداخل
                for msg_idx, msg in enumerate(messages):
                    # فحص إذا كانت الرسالة null أو ليست dict
                    if msg is None or not isinstance(msg, dict):
                        print(f"🚨 [السطر {idx+1}][الرسالة {msg_idx}]: الرسالة فارغة null أو ليست كائن!")
                        null_count += 1
                        errors += 1
                        continue
                    
                    # فحص وجود المفاتيح الأساسية role و content
                    if "role" not in msg or "content" not in msg:
                        print(f"🚨 [السطر {idx+1}][الرسالة {msg_idx}]: حقول ناقصة! يجب وجود 'role' و 'content'")
                        wrong_format_count += 1
                        errors += 1
                        continue
                        
                    # فحص القيم إذا كانت فارغة أو null
                    role_val = msg["role"]
                    content_val = msg["content"]
                    
                    if role_val is None or content_val is None:
                        print(f"🚨 [السطر {idx+1}][الرسالة {msg_idx}]: قيمة حقل role أو content تحتوي على null!")
                        null_count += 1
                        errors += 1
                        continue
                        
                    # فحص محتوى النص إذا كان مجرد فراغات وايت سبيس
                    if isinstance(content_val, str) and not content_val.strip():
                        print(f"🚨 [السطر {idx+1}][الرسالة {msg_idx}]: الـ content عبارة عن نص فارغ (Spaces/Empty)!")
                        null_count += 1
                        errors += 1
                        
                    # تأكيد الأدوار الصحيحة لـ Qwen 3.5
                    if role_val not in ["system", "user", "assistant"]:
                        print(f"🚨 [السطر {idx+1}][الرسالة {msg_idx}]: دور غير مدعوم ({role_val})! المدعوم: system, user, assistant")
                        wrong_format_count += 1
                        errors += 1

            except json.JSONDecodeError:
                print(f"🚨 [السطر {idx+1}]: خطأ في الـ Syntax! ليس ملف JSON صالح.")
                wrong_format_count += 1
                errors += 1
                
    # النتيجة النهائية للفحص
    if errors == 0:
        print(f"✅ فحص ناجح 100%! الملف سليم تماماً ومتوافق مع Qwen 3.5 و Unsloth.")
        print(f"📊 إجمالي الأسطر المفحوصة والسليمة: {total_rows}")
        return True
    else:
        print(f"\n❌ تم العثور على أخطاء بحاجة لإصلاح:")
        print(f"   - عدد القيم الفارغة أو الـ null: {null_count}")
        print(f"   - عدد التنسيقات الخاطئة (Wrong Format): {wrong_format_count}")
        print(f"   - إجمالي الأخطاء الكلي: {errors} في أصل {total_rows} سطر.")
        return False

# تشغيل الفحص على الملفين
train_ok = validate_qwen_dataset(train_path)
eval_ok = validate_qwen_dataset(eval_path)

if train_ok and eval_ok:
    print("\n🎉 الداتا نظيفة وجاهزة للتدريب 100% من دون أي ريسك! فيك تبلش بـ Unsloth وأنت مطّمن.")
else:
    print("\n⚠️ انتبه! يرجى مراجعة الأخطاء المطبوعة فوق وتصحيحها قبل تشغيل الـ Trainer.")

--- ⏳ جاري الفحص الدقيق لملف: train.jsonl ---
✅ فحص ناجح 100%! الملف سليم تماماً ومتوافق مع Qwen 3.5 و Unsloth.
📊 إجمالي الأسطر المفحوصة والسليمة: 13499

--- ⏳ جاري الفحص الدقيق لملف: eval.jsonl ---
✅ فحص ناجح 100%! الملف سليم تماماً ومتوافق مع Qwen 3.5 و Unsloth.
📊 إجمالي الأسطر المفحوصة والسليمة: 1500

🎉 الداتا نظيفة وجاهزة للتدريب 100% من دون أي ريسك! فيك تبلش بـ Unsloth وأنت مطّمن.

In [13]:
import os

train_path = r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed\train.jsonl"
temp_path = train_path + ".tmp"

print("⏳ جاري تنظيف وتصحيح ملف train.jsonl تلقائياً...")

cleaned_count = 0
with open(train_path, "r", encoding="utf-8") as f_in:
    with open(temp_path, "w", encoding="utf-8") as f_out:
        for idx, line in enumerate(f_in):
            # السطر 7789 بالـ Index ببلش من 7788 (لأن الـ Loop بتبلش من 0)
            # بس للاحتياط، السكربت رح يتخطى السطر اللي فيه المشكلة بالظبط
            if idx == 7788:
                print(f"✅ تم حذف السطر الفاسد رقم {idx+1} بنجاح.")
                continue
            f_out.write(line)
            cleaned_count += 1

# استبدال الملف القديم بالملف النظيف الجديد
os.remove(train_path)
os.rename(temp_path, train_path)

print(f"🎉 انتهى التصحيح! الملف الآن سليم تماماً وفيه {cleaned_count} سطر جاهز.")

⏳ جاري تنظيف وتصحيح ملف train.jsonl تلقائياً...
✅ تم حذف السطر الفاسد رقم 7789 بنجاح.
🎉 انتهى التصحيح! الملف الآن سليم تماماً وفيه 13499 سطر جاهز.

In [15]:
import json
import random
import os

train_path = r"C:\Users\user\Desktop\Lebanese Assistant\lebanese-assistant\datasets\processed\train.jsonl"

print("--- ⚙️ محاكاة فحص التنسيق لـ Qwen 3.5 و Unsloth ---")

if not os.path.exists(train_path):
    print("❌ خطأ: ملف train.jsonl غير موجود على المسار!")
else:
    # 1. قراءة عينات عشوائية من الملف
    samples = []
    with open(train_path, "r", encoding="utf-8") as f:
        lines = [line for line in f if line.strip()]
        # سحب 2 عينات عشوائية لنشوف شكلهم
        samples = random.sample(lines, min(2, len(lines)))
    
    # 2. محاكاة الـ Chat Template الافتراضي لـ Qwen 3.5 (ChatML)
    for idx, sample_line in enumerate(samples):
        data = json.loads(sample_line)
        messages = data["messages"]
        
        print(f"\n================ 👁️ عينة محاكاة رقم {idx+1} ================")
        print("📥 [الشكل بملف الـ JSONL]:")
        print(json.dumps(data, ensure_ascii=False, indent=2)[:400] + "...\n")
        
        print("🚀 [كيف سيري الموديل النص بفضل الـ ChatML الخاص بـ Qwen 3.5]:")
        
        # بناء يدوي يحاكي الـ Tokenizer الافتراضي لعائلة Qwen
        simulated_chat_template = ""
        for msg in messages:
            role = msg["role"]
            content = msg["content"]
            
            # قالب الـ ChatML الرسمي لـ Qwen 3.5 بيستخدم هول الـ Tokens بالظبط بالخلفية
            simulated_chat_template += f"<|im_start|>{role}\n{content}<|im_end|>\n"
            
        print(simulated_chat_template)
        print("=========================================================")

    print("\n✅ النتيجة التقنية:")
    print("1. حقل الـ 'messages' موجود كـ List وهيدا المطلوب لـ Unsloth.")
    print("2. الأدوار مقسمة لـ 'role' و 'content' داخل Dictionaries منفصلة.")
    print("3. الـ System Prompt موجود بأول كل سطر لتثبيت الهوية اللبنانية.")
    print("🔥 الداتا متطابقة 100% مع معايير Qwen 3.5 الافتراضية وجاهزة للـ Trainer فوراً!")

--- ⚙️ محاكاة فحص التنسيق لـ Qwen 3.5 و Unsloth ---

================ 👁️ عينة محاكاة رقم 1 ================
📥 [الشكل بملف الـ JSONL]:
{
  "messages": [
    {
      "role": "system",
      "content": "أنت مساعد ذكي لبناني. بتفهم وبتتكلم بالعامية اللبنانية وباللغة الإنجليزية بطلاقة، وأسلوبك دايماً قريب للقلب ومساعد."
    },
    {
      "role": "user",
      "content": "Have you used aws-vault for securely managing project credentials? If so, how does it compare to other methods mentioned in the text? Answer according to: I've been...

🚀 [كيف سيري الموديل النص بفضل الـ ChatML الخاص بـ Qwen 3.5]:
<|im_start|>system
أنت مساعد ذكي لبناني. بتفهم وبتتكلم بالعامية اللبنانية وباللغة الإنجليزية بطلاقة، وأسلوبك دايماً قريب للقلب ومساعد.<|im_end|>
<|im_start|>user
Have you used aws-vault for securely managing project credentials? If so, how does it compare to other methods mentioned in the text? Answer according to: I've been trying to get a manageable system for dealing with projects that need a lot of settings, some of which are secrets such as credentials. In general, environment variables are the most widely-supported mechanism. They have many shortcomings: they are exposed by the OS to other processes running as your user or root via the /proc filesystem (at least on linux), don't have data types other than strings, can't express nesting or arrays easily, etc. However, they can get the job done if you keep things simple.
So I feel pretty good that this is securely off disk. I would copy and paste this into my shell and go about my work. However, these commands then get put into my shell history which are clear text files. I wanted something this convenient but keeping secrets out of my shell history.
Which I set up as a keyboard macro so I type epb,,, keyboard maestro detects the double comma and looks up the proper snippet to expand the text. The eval tells the shell to execute the code and the pbpaste bit outputs the text I just copied from 1password.
So this is better. Some shells allow omitting a command from history by typing a leading space in front of it, just FYI but I felt that was too error prone to use consistently.
It's still not ideal as stuff lives in memory probably longer than it should, and the mechanism to clear things is to exit the shell, which I don't do regularly enough because there's usually state in the shell I don't want to have to re-setup like activating python virtualenvs, etc. It's also possible to unintentionally copy some other text before you paste it into the terminal, thus shooting yourself with your eval footgun.
Got something better to suggest?
Side note for zsh: setopt interactivecomments will avoid annoying errors when you paste snippets with comments into an interactive shell.
It looks like aws-vault is a handy tool for this as well. I've started using it on 2 projects and so far so good, but it only handles the AWS creds, not randow other project vars.<|im_end|>
<|im_start|>assistant
I haven't personally used aws-vault for managing project credentials. However, based on the information provided in the text, aws-vault seems to be a more secure and convenient solution than using environment variables or copying and pasting into the shell. With aws-vault, project credentials are stored encrypted on disk and are only unlocked when needed with a specific command. This means that they are not stored in plain text or in memory, reducing the risk of exposure. Additionally, aws-vault can be used to manage aws credentials specifically, which is useful for projects that require access to aws resources. However, aws-vault does not handle other project variables, so depending on the project requirements, additional tools may be needed to manage those credentials.<|im_end|>
<|im_start|>user
Can you provide more information on how to set up and use aws-vault for managing project credentials? I am interested in learning more about this tool and how it can be incorporated into my current workflow.<|im_end|>
<|im_start|>assistant
Sure! Here are the basic steps for setting up and using aws-vault:

1. Install aws-vault: You can download and install aws-vault from the official GitHub page: https://github.com/99designs/aws-vault#installation.

2. Create a new aws-vault profile: You can create a new aws-vault profile using the following command:

   `aws-vault add <profile-name>`

   Replace `<profile-name>` with the name of the AWS profile you want to create.

3. Add credentials to the new aws-vault profile: You can add credentials to the new aws-vault profile using the following command:

   `aws-vault edit <profile-name>`

   This will open up a text editor where you can enter the AWS access key ID and secret access key for your profile. You can also set additional configuration options like the default region and session duration.

4. Use the aws-vault profile: Once you have created and configured an aws-vault profile, you can use it to run AWS CLI commands securely. You can start a new shell session with the aws-vault credentials by using the following command:

   `aws-vault exec <profile-name> -- <shell-command>`

   Replace `<profile-name>` with the name of the aws-vault profile you want to use, and `<shell-command>` with the AWS CLI command you want to run.

   For example, if you want to list all the EC2 instances in your AWS account using the aws-vault profile named "my-profile", you can use the following command:

   `aws-vault exec my-profile -- aws ec2 describe-instances`

That's it! Using aws-vault, you can securely manage your AWS credentials and run AWS CLI commands without exposing your credentials to the shell or other processes.<|im_end|>
<|im_start|>user
Can you remind me of the advantages of using aws-vault over other methods for securely managing project credentials mentioned in the text?<|im_end|>
<|im_start|>assistant
Certainly! Here are some of the advantages of using aws-vault over other methods for securely managing project credentials:

1. Encryption: With aws-vault, project credentials are stored encrypted on disk and are only unlocked when needed with a specific command. This means that they are not stored in plain text or in memory, reducing the risk of exposure.

2. Convenience: aws-vault helps to reduce the friction of managing multiple AWS accounts by providing a convenient way to switch between them with a single command. This can be especially useful for developers who work with multiple AWS accounts or have multiple environments (e.g., production, staging, development), each with its own set of credentials.

3. Security: aws-vault provides an added layer of security by requiring a password or passphrase to unlock the credentials. This ensures that only authorized users can access the credentials, even if someone gains access to the machine or file system.

4. Ease of use: aws-vault integrates seamlessly with the AWS CLI and SDKs, so developers can continue to use the familiar AWS tools and workflows they are already comfortable with.

5. Specific to AWS credentials: aws-vault was designed specifically to manage AWS credentials and integrates well with AWS IAM roles and policies. Other methods mentioned in the text, like environment variables, may work for other types of credentials but may not be as well-suited to managing AWS IAM resources.<|im_end|>
<|im_start|>user
Can you provide any example of using aws-vault with multiple AWS accounts? How does it help to manage credentials for different environments such as production, staging, and development?<|im_end|>
<|im_start|>assistant
<think>

</think>

Sure, I can provide an example of using aws-vault with multiple AWS accounts for different environments.

Suppose you work for a company that has AWS accounts for production, staging, and development environments. Each environment requires its own set of AWS credentials (access key ID and secret access key) to access the AWS resources in that environment.

Here's how you can use aws-vault to manage these credentials:

1. Create an aws-vault profile for each environment: You can create a separate aws-vault profile for each environment (e.g., production, staging, development) using the `aws-vault add` command. For example:

   ```
   aws-vault add production-profile
   aws-vault add staging-profile
   aws-vault add development-profile
   ```

2. Add the AWS credentials for each environment to the corresponding aws-vault profile: You can use the `aws-vault edit` command to add the AWS credentials (access key ID and secret access key) for each environment to the corresponding aws-vault profile. For example:

   ```
   aws-vault edit production-profile
   aws-vault edit staging-profile
   aws-vault edit development-profile
   ```

3. Use the appropriate aws-vault profile for each environment: You can use the `aws-vault exec` command to run AWS CLI commands with the appropriate aws-vault profile for the environment you want to work with. For example:

   ```
   aws-vault exec production-profile -- aws s3 ls
   aws-vault exec staging-profile -- aws ec2 describe-instances
   aws-vault exec development-profile -- aws lambda list-functions
   ```

   The `aws-vault exec` command will launch a new shell with the AWS credentials for the specified profile set as environment variables. This allows you to use familiar AWS CLI commands while ensuring that you are using the correct set of AWS credentials for the environment you are working with.

Using aws-vault in this way can help you to manage multiple AWS accounts and credentials more easily and securely. By using separate aws-vault profiles for each environment, you can avoid accidentally using the wrong set of credentials and reduce the risk of exposing credentials to unauthorized users. Additionally, aws-vault provides a convenient way to switch between AWS credentials for different environments with a single command.<|im_end|>

=========================================================

================ 👁️ عينة محاكاة رقم 2 ================
📥 [الشكل بملف الـ JSONL]:
{
  "messages": [
    {
      "role": "system",
      "content": "أنت مساعد ذكي لبناني. بتفهم وبتتكلم بالعامية اللبنانية وباللغة الإنجليزية بطلاقة، وأسلوبك دايماً قريب للقلب ومساعد."
    },
    {
      "role": "user",
      "content": "Is there a monthly newsletter that contains new funding opportunities? Answer according to: Find links to suggested resources for funding opportunities.\nEvery mont...

🚀 [كيف سيري الموديل النص بفضل الـ ChatML الخاص بـ Qwen 3.5]:
<|im_start|>system
أنت مساعد ذكي لبناني. بتفهم وبتتكلم بالعامية اللبنانية وباللغة الإنجليزية بطلاقة، وأسلوبك دايماً قريب للقلب ومساعد.<|im_end|>
<|im_start|>user
Is there a monthly newsletter that contains new funding opportunities? Answer according to: Find links to suggested resources for funding opportunities.
Every monthly issue of the Research Development & Grant Writing News, accessible at this UCSD-only website, contains a compilation of new funding opportunities.
For more information contact researchdevelopment@ucsd.edu.<|im_end|>
<|im_start|>assistant
I do not have access to websites restricted to ucsd-only users nor can I send emails. However, there are several resources that can provide funding opportunity alerts such as grants.gov, grantwatch, foundation directory online, and pivot. Additionally, many federal agencies and private foundations have email subscription services that send regular updates on their funding opportunities.<|im_end|>
<|im_start|>user
Can you provide me with the links to Grants.gov, GrantWatch, Foundation Directory Online, and Pivot so I can start receiving alerts for new funding opportunities?<|im_end|>
<|im_start|>assistant
Sure, here are the links to those sites:

- Grants.gov: https://www.grants.gov/
- GrantWatch: https://www.grantwatch.com/
- Foundation Directory Online: https://fconline.foundationcenter.org/
- Pivot: https://pivot.proquest.com/

You can also search for funding opportunities on these websites and set up alerts for new opportunities that match your research interests.<|im_end|>
<|im_start|>user
Can you suggest which website would be the best for finding funding opportunities for research in the social sciences?<|im_end|>
<|im_start|>assistant
<think>

</think>

Certainly! Here are some recommendations for finding funding opportunities specific to the social sciences:

1. National Science Foundation (NSF): The NSF's Social, Behavioral and Economic Sciences (SBE) directorate supports research in the social sciences, including anthropology, economics, political science, psychology, and sociology. You can find current funding opportunities on their website: https://www.nsf.gov/funding/programs.jsp?org=SBE. 2. Social Science Research Council (SSRC): The SSRC funds research in the social sciences, with a focus on interdisciplinary and international projects. They offer a variety of funding programs, including fellowships, small grants, and large-scale research initiatives. You can find their current opportunities here: https://www.ssrc.org/fellowships/. 3. American Psychological Association (APA): The APA offers a number of funding opportunities for research in psychology, including grants for early career researchers, travel grants, and dissertation research awards. You can find their current funding opportunities here: https://www.apa.org/apf/funding/index. 4. National Endowment for the Humanities (NEH): While the NEH primarily supports projects in the humanities, they also fund some projects on social science topics, such as history and cultural studies. You can find their current funding opportunities here: https://www.neh.gov/grants. These are just a few examples of funding opportunities for social science research, and there are many more out there. You can also use the resources I mentioned earlier (Grants.gov, GrantWatch, Foundation Directory Online, and Pivot) to search for funding opportunities in specific areas of the social sciences.<|im_end|>

=========================================================

✅ النتيجة التقنية:
1. حقل الـ 'messages' موجود كـ List وهيدا المطلوب لـ Unsloth.
2. الأدوار مقسمة لـ 'role' و 'content' داخل Dictionaries منفصلة.
3. الـ System Prompt موجود بأول كل سطر لتثبيت الهوية اللبنانية.
🔥 الداتا متطابقة 100% مع معايير Qwen 3.5 الافتراضية وجاهزة للـ Trainer فوراً!